module.exports = {
    USER: 0,
    TRANSACTIOn: 0,
    USER_TRANSACTION: 0,

    EXPENSE_TYPE_EQUAL: "EQUAL",
    EXPENSE_TYPE_EXACT: "EXACT",
    TRANSACTIO_TYPE_CREDIT: "CREDIT",
    TRANSACTIO_TYPE_DEBIT: "DEBIT"
};